### ISSUE TITLE
Deprecated messages with PHP 8.2

### ISSUE THREAD

**Issue by wernergusset** [litzinger/URL-Helper#19]
EE 7.3.12 und URL Helper 1.30 with PHP 8.2 gives this messages:

Deprecated
Creation of dynamic property Url_helper_ext::$config is deprecated
user/addons/url_helper/ext.url_helper.php, line 71

Severity: E_DEPRECATED
Deprecated
Creation of dynamic property Url_helper_ext::$prefix is deprecated
user/addons/url_helper/ext.url_helper.php, line 72

Severity: E_DEPRECATED

**Comment by creativearc-paul** [comment]
Also noticing this in PHP 8.2

**Comment by litzinger** [comment]
Fixed
